### ISSUE TITLE
Révision du code dans Facture

### ISSUE THREAD

**Issue by p123abc** [DannyChaotix/TP1AQ#1]
La prise en charge des erreurs dans la classe **Facture** ne marche pas. Ajouter ou modifier le code pour respecter les demande demander par le professeurs. Voir **Travail pratique – Partie 3**

Il peut y avoir des commandes incorrectes. Une commande est incorrecte si :

- Le nom du client ou le plat n’existe pas (vu précédemment).

- Le format d’un client, d’un plat ou d’une commande n’est pas respecté.

- Des chiffres sont erronés (prix du plat, quantité de plats commandés).

**Comment by David-Provost** [comment]
Ajout de testes pour trouver / formater les clients et les plats.
Correction des variables
